# Generated by Django 3.0.8 on 2020-08-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('tipo', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, null=True)),
                ('fono', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('representante', models.CharField(max_length=200)),
                ('fono', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('aporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.Aporte')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Empresa')),
                ('rut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.Empleado')),
            ],
        ),
    ]
