# Generated by Django 3.0.8 on 2020-08-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='nombre',
            field=models.CharField(default='Campana numero 1', max_length=200),
            preserve_default=False,
        ),
    ]
